#!/usr/bin/env python3
"""Generate include/ids-k-table.h from the paper's polynomial (see ids_model)."""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import ids_model  # noqa: E402

out = pathlib.Path(__file__).parent.parent / "include" / "ids-k-table.h"
tab = ids_model.k_table()
lines = [
    "/* GENERATED by scripts/gen_k_table.py - do not edit.",
    " *",
    " * k(x) = -5e-5 x^4 + 0.0037 x^3 - 0.0899 x^2 + 0.9281 x - 0.7903",
    " * (Farzaneh et al. 2019, eq. 2), x = number of neighbours, scaled by 1000",
    " * and clamped at 0. Index with min(x, IDS_K_TABLE_MAX). */",
    "#ifndef IDS_K_TABLE_H_",
    "#define IDS_K_TABLE_H_",
    "#include <stdint.h>",
    f"#define IDS_K_TABLE_MAX {ids_model.K_TABLE_MAX}",
    "static const uint16_t ids_k_x1000[IDS_K_TABLE_MAX + 1] = {",
]
for i in range(0, len(tab), 8):
    chunk = ", ".join(f"{v:5d}" for v in tab[i:i + 8])
    lines.append(f"  {chunk},  /* x = {i}..{min(i + 7, len(tab) - 1)} */")
lines += ["};", "#endif /* IDS_K_TABLE_H_ */", ""]
out.write_text("\n".join(lines))
print(f"wrote {out}: k(2)={tab[2]/1000} k(5)={tab[5]/1000} k(10)={tab[10]/1000} k(20)={tab[20]/1000} k(40)={tab[40]/1000}")
