/* GENERATED by scripts/gen_k_table.py - do not edit.
 *
 * k(x) = -5e-5 x^4 + 0.0037 x^3 - 0.0899 x^2 + 0.9281 x - 0.7903
 * (Farzaneh et al. 2019, eq. 2), x = number of neighbours, scaled by 1000
 * and clamped at 0. Index with min(x, IDS_K_TABLE_MAX). */
#ifndef IDS_K_TABLE_H_
#define IDS_K_TABLE_H_
#include <stdint.h>
#define IDS_K_TABLE_MAX 40
static const uint16_t ids_k_x1000[IDS_K_TABLE_MAX + 1] = {
      0,    52,   735,  1281,  1708,  2034,  2276,  2450,  /* x = 0..7 */
   2570,  2650,  2701,  2734,  2758,  2783,  2815,  2860,  /* x = 8..15 */
   2923,  3008,  3118,  3252,  3412,  3596,  3801,  4025,  /* x = 16..23 */
   4262,  4506,  4750,  4986,  5205,  5394,  5543,  5638,  /* x = 24..31 */
   5664,  5607,  5449,  5172,  4757,  4184,  3432,  2476,  /* x = 32..39 */
   1294,  /* x = 40..40 */
};
#endif /* IDS_K_TABLE_H_ */
